//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class TestingSystemEntities2 : DbContext
{
    public TestingSystemEntities2()
        : base("name=TestingSystemEntities2")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<MCQOption> MCQOptions { get; set; }
    public virtual DbSet<Program> Programs { get; set; }
    public virtual DbSet<Question> Questions { get; set; }
    public virtual DbSet<Sub> Subs { get; set; }
    public virtual DbSet<Topic> Topics { get; set; }
}
